Mission04_bwh46/Models/GraderModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission05_bwh46.Models
{
    //This is what we have to find the data for the form. 
    public class GraderModel
    {
        // Each entry must be between 0 and 100 and that is what the range is doing
        [Range(0, 100)]
        public int Assignments { get; set; }

        [Range(0, 100)]
        public int Group { get; set; }

        [Range(0, 100)]
        public int Quizzes { get; set; }

        [Range(0, 100)]
        public int Midterm { get; set; }

        [Range(0, 100)]
        public int Final { get; set; }

        [Range(0, 100)]
        public int Intex { get; set; }

    }
}

Mission04_bwh46/Controllers/GradesController.cs
using Microsoft.AspNetCore.Mvc;
using Mission05_bwh46.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_bwh46.Controllers
{
    public class GradesController : Controller

        // Our default view that is displayed is Index
    {
        public IActionResult Index()
        {
            return View();
        }

        //Have get req and post req for the view Grader bc this is where we have the form to be submitted

        [HttpGet]
        public IActionResult Grader()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Grader(GraderModel model)
        {
            return View();
        }
    }
}

Mission04_bwh46/Views/Grades/Grader.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
    ViewData["Text"] = "Let's see that GPA!";
}
@model GraderModel;


<!--This form is submitted to the js file-->
<!--The asp-for is used for the model called GraderModel, which will ensure the entries for the form are btwn 0-100-->
<h2>Grade Calculator: </h2>
<form method="post">
    <label>Assignments:</label>
    <input type="number" id="assignment" asp-for="Assignments"/><br />
    <label>Group Project:</label>
    <input type="number" id="group" asp-for="Group"/><br />
    <label>Quizzes:</label>
    <input type="number" id="quizzes" asp-for="Quizzes"/><br />
    <label>Midterm Exam:</label>
    <input type="number" id="midterm" asp-for="Midterm"/><br />
    <label>Final Exam:</label>
    <input type="number" id="final" asp-for="Final"/><br />
    <label>INTEX:</label>
    <input type="number" id="intex" asp-for="Intex"/>
    <p id="totalGrade"></p><br /> <!--This is where the final grade will go using the id, changed in the js file-->
    <input id="calcGrade" type="submit" value="Submit" />

    <!--this tells the user what is wrong with the form if it is not accepted (data validation)-->
    <div asp-validation-summary="All"></div>
</form>
<!--including jquery, js file, bootstrap-->
<script src="~/js/Grades.js"></script>

Mission04_bwh46/Views/Grades/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    //this is what data is set for the title of the webpage and the text within a header tag in the _Layout file
    // This is our default page

    ViewData["Title"] = "Homepage";
    ViewData["Text"] = "Some info about me!";
}


<img src="~/img/doingSomethingFun.jpg" width="50%" height="50%" /><br /><br />
<h2>What I Hope to Get Out of IS 413</h2>

<!--What I hope to get out of class paragraph-->
<p>
    IS 413 is one with a daunting reputation. The first day of class
    we were shown a picture of an intricate airplane that was intended to
    replicate the complexity of the language we would be learning. I
    hope to get out of this class an affirmation that regardless of how
    intense the plane, I can learn to fly. IS 413 will hopefully make me, as
    the professors love to say, <i>dangerous</i>.
</p>

<!--top 3 jobs req-->
<h2>Top 3 jobs after I graduate:</h2>
<ul>
    <li>Technical Consultant</li>
    <li>Data Analyst</li>
    <li>Data Engineer</li>
</ul>

Mission04_bwh46/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--This page is inherited by the other views.-->
<html>
<head>
    <meta charset="utf-8" />
    <!--The title of the page is changed via razor code-->
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="~/img/04favicon.jpg" />
    <!--including the bootstrap css as well as my own css to change the header tag-->
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/benStyles.css" rel="stylesheet" />
</head>

<body>
    <!--The header tag is also changed via razor code-->
    <header>@ViewData["Text"]</header>
<nav>
    <!--navigation to the two pages to be displayed on every page of the website-->
    <a asp-controller="Grades" asp-action="Index">Home</a>
    <a asp-controller="Grades" asp-action="Grader">Grades</a>
</nav>
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
</body>
</html>